# Generated by Django 4.1.2 on 2022-10-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='membership_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
