# Generated by Django 4.1.2 on 2022-10-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_account_membership_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_progress',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
