# Generated by Django 4.1.2 on 2022-10-30 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='membership_date',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user_progress',
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_progress', models.IntegerField(default=0)),
                ('membership_date', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
            ],
        ),
    ]
