# Generated by Django 4.1.2 on 2022-10-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_account_membership_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='user_progress',
        ),
        migrations.AddField(
            model_name='account',
            name='user_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membership',
            name='plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
