# Generated by Django 4.1.2 on 2022-10-30 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_membership_user_progress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='account',
            new_name='account_link',
        ),
    ]
