# Generated by Django 4.1.2 on 2022-10-30 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_account_membership_account_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='account_link',
            new_name='account',
        ),
    ]
