# Generated by Django 4.1.2 on 2022-10-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_account_link_membership_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='membership_date',
            new_name='date',
        ),
    ]
