# Generated by Django 4.1.2 on 2022-10-13 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stripe_product_id', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('stripe_price_id', models.CharField(max_length=150)),
                ('membership_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_app.membershipplan')),
            ],
        ),
    ]
