# Generated by Django 4.1.2 on 2022-10-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
