# Generated by Django 4.1.2 on 2022-10-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0003_membershipplan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
