# Generated by Django 4.1.2 on 2022-10-22 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0004_alter_membershipplan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplanprice',
            name='membership_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='gym_app.membershipplan'),
        ),
    ]
