# Generated by Django 3.2.9 on 2022-10-29 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0005_alter_membershipplanprice_membership_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplanprice',
            name='membership_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_app.membershipplan'),
        ),
    ]
