# Generated by Django 3.2.9 on 2022-10-29 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0007_alter_membershipplanprice_membership_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershipplan',
            old_name='stripe_product_id',
            new_name='stripe_product',
        ),
        migrations.RenameField(
            model_name='membershipplanprice',
            old_name='stripe_price_id',
            new_name='stripe_price',
        ),
    ]
